name: Build Open GApps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3.2.2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Sync submodules
      run: |
        git submodule update --init --recursive
        ./download_sources.sh --shallow

    - name: Build Open GApps
      run: make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4.5.0
      with:
        name: open-gapps
        path: out/
